### ISSUE TITLE
can't compile with theos

### ISSUE THREAD

**Issue by Mabdelwanis** [AzzouDuGhetto/Coeus#3]
hello dear trying to compile it with theos always get this error 

 make clean package
==> Cleaning…
> Making clean in Tweak…
==> Cleaning…
> Making clean in Prefs…
==> Cleaning…
> Making all in Tweak…
> Making all for bundle Coeus…
==> Copying resource directories into the bundle wrapper…
==> Compiling CoeusLAEvent.m (arm64e)…
==> Compiling CoeusLAEvent.m (arm64)…
==> Compiling CoeusUILabeledRoundButtonViewController.m (arm64e)…
In file included from CoeusUILabeledRoundButtonViewController.m:1:
In file included from ./CoeusUILabeledRoundButtonViewController.h:1:
/home/mo/theos/include/ControlCenterUIKit/CCUIRoundButton.h:14:41: error: declaration of 'UIGestureRecognizerDelegate' must be imported from module 'UIKit.UIGestureRecognizer' before it is required
@interface CCUIRoundButton : UIControl <UIGestureRecognizerDelegate> {
                                        ^
/home/mo/theos/sdks/iPhoneOS14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGestureRecognizer.h:89:11: note: previous declaration is here
@protocol UIGestureRecognizerDelegate <NSObject>
          ^
1 error generated.
make[4]: *** [/home/mo/theos/makefiles/instance/rules.mk:209: /home/mo/tweaks/Coeus/.theos/obj/debug/arm64e/CoeusUILabeledRoundButtonViewController.m.3e4f5170.o] Error 1
make[4]: *** Waiting for unfinished jobs....
==> Compiling CoeusUIModuleContentViewController.m (arm64e)…
In file included from CoeusUIModuleContentViewController.m:1:
In file included from ./CoeusUIModuleContentViewController.h:1:
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:11:51: error: cannot find protocol declaration for 'NSObject'
@protocol CCUIContentModuleContentViewController <NSObject>
                                                  ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:12:32: error: unknown type name 'CGFloat'
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
                               ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:13:32: error: unknown type name 'CGFloat'
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
                               ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:14:32: error: unknown type name 'BOOL'
@property (nonatomic,readonly) BOOL providesOwnPlatter;
                               ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:16:4: error: expected a type
- (BOOL)shouldBeginTransitionToExpandedContentModule;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:19:46: error: expected a type
- (void)willTransitionToExpandedContentMode:(BOOL)arg1;
                                             ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:20:4: error: expected a type
- (BOOL)shouldFinishTransitionToExpandedContentModule;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:21:45: error: expected a type
- (void)didTransitionToExpandedContentMode:(BOOL)arg1;
                                            ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:22:4: error: expected a type
- (BOOL)canDismissPresentedContent;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:23:42: error: expected a type
- (void)dismissPresentedContentAnimated:(BOOL)arg1 completion:(/*^block*/ id)arg2;
                                         ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:24:4: error: expected a type
- (CGFloat)preferredExpandedContentWidth;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:25:4: error: expected a type
- (BOOL)providesOwnPlatter;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:30:4: error: expected a type
- (CGFloat)preferredExpandedContentHeight;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:12:40: error: type of property 'preferredExpandedContentHeight' ('int') does not match type of accessor 'preferredExpandedContentHeight' ('id')
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
                                       ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:30:1: note: declared here
- (CGFloat)preferredExpandedContentHeight;
^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:13:40: error: type of property 'preferredExpandedContentWidth' ('int') does not match type of accessor 'preferredExpandedContentWidth' ('id')
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
                                       ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:24:1: note: declared here
- (CGFloat)preferredExpandedContentWidth;
^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:14:37: error: type of property 'providesOwnPlatter' ('int') does not match type of accessor 'providesOwnPlatter' ('id')
@property (nonatomic,readonly) BOOL providesOwnPlatter;
                                    ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:25:1: note: declared here
- (BOOL)providesOwnPlatter;
^
In file included from CoeusUIModuleContentViewController.m:1:
In file included from ./CoeusUIModuleContentViewController.h:4:
In file included from ./CoeusUILabeledRoundButtonViewController.h:1:
/home/mo/theos/include/ControlCenterUIKit/CCUIRoundButton.h:14:41: error: declaration of 'UIGestureRecognizerDelegate' must be imported from module 'UIKit.UIGestureRecognizer' before it is required
@interface CCUIRoundButton : UIControl <UIGestureRecognizerDelegate> {
                                        ^
/home/mo/theos/sdks/iPhoneOS14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGestureRecognizer.h:89:11: note: previous declaration is here
@protocol UIGestureRecognizerDelegate <NSObject>
          ^
In file included from CoeusUIModuleContentViewController.m:1:
./CoeusUIModuleContentViewController.h:8:41: error: property type 'CGFloat' (aka 'double') is incompatible with type 'int' inherited from 'CCUIContentModuleContentViewController' [-Werror,-Wincompatible-property-type]
@property (nonatomic, readonly) CGFloat preferredExpandedContentHeight;
                                        ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:12:40: note: property declared here
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
                                       ^
In file included from CoeusUIModuleContentViewController.m:1:
./CoeusUIModuleContentViewController.h:9:41: error: property type 'CGFloat' (aka 'double') is incompatible with type 'int' inherited from 'CCUIContentModuleContentViewController' [-Werror,-Wincompatible-property-type]
@property (nonatomic, readonly) CGFloat preferredExpandedContentWidth;
                                        ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:13:40: note: property declared here
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[4]: *** [/home/mo/theos/makefiles/instance/rules.mk:209: /home/mo/tweaks/Coeus/.theos/obj/debug/arm64e/CoeusUIModuleContentViewController.m.3e4f5170.o] Error 1
==> Compiling CoeusUIModuleContentViewController.m (arm64)…
In file included from CoeusUIModuleContentViewController.m:1:
In file included from ./CoeusUIModuleContentViewController.h:1:
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:11:51: error: cannot find protocol declaration for 'NSObject'
@protocol CCUIContentModuleContentViewController <NSObject>
                                                  ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:12:32: error: unknown type name 'CGFloat'
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
                               ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:13:32: error: unknown type name 'CGFloat'
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
                               ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:14:32: error: unknown type name 'BOOL'
@property (nonatomic,readonly) BOOL providesOwnPlatter;
                               ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:16:4: error: expected a type
- (BOOL)shouldBeginTransitionToExpandedContentModule;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:19:46: error: expected a type
- (void)willTransitionToExpandedContentMode:(BOOL)arg1;
                                             ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:20:4: error: expected a type
- (BOOL)shouldFinishTransitionToExpandedContentModule;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:21:45: error: expected a type
- (void)didTransitionToExpandedContentMode:(BOOL)arg1;
                                            ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:22:4: error: expected a type
- (BOOL)canDismissPresentedContent;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:23:42: error: expected a type
- (void)dismissPresentedContentAnimated:(BOOL)arg1 completion:(/*^block*/ id)arg2;
                                         ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:24:4: error: expected a type
- (CGFloat)preferredExpandedContentWidth;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:25:4: error: expected a type
- (BOOL)providesOwnPlatter;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:30:4: error: expected a type
- (CGFloat)preferredExpandedContentHeight;
   ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:12:40: error: type of property 'preferredExpandedContentHeight' ('int') does not match type of accessor 'preferredExpandedContentHeight' ('id')
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
                                       ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:30:1: note: declared here
- (CGFloat)preferredExpandedContentHeight;
^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:13:40: error: type of property 'preferredExpandedContentWidth' ('int') does not match type of accessor 'preferredExpandedContentWidth' ('id')
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
                                       ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:24:1: note: declared here
- (CGFloat)preferredExpandedContentWidth;
^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:14:37: error: type of property 'providesOwnPlatter' ('int') does not match type of accessor 'providesOwnPlatter' ('id')
@property (nonatomic,readonly) BOOL providesOwnPlatter;
                                    ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:25:1: note: declared here
- (BOOL)providesOwnPlatter;
^
In file included from CoeusUIModuleContentViewController.m:1:
In file included from ./CoeusUIModuleContentViewController.h:4:
In file included from ./CoeusUILabeledRoundButtonViewController.h:1:
/home/mo/theos/include/ControlCenterUIKit/CCUIRoundButton.h:14:41: error: declaration of 'UIGestureRecognizerDelegate' must be imported from module 'UIKit.UIGestureRecognizer' before it is required
@interface CCUIRoundButton : UIControl <UIGestureRecognizerDelegate> {
                                        ^
/home/mo/theos/sdks/iPhoneOS14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGestureRecognizer.h:89:11: note: previous declaration is here
@protocol UIGestureRecognizerDelegate <NSObject>
          ^
In file included from CoeusUIModuleContentViewController.m:1:
./CoeusUIModuleContentViewController.h:8:41: error: property type 'CGFloat' (aka 'double') is incompatible with type 'int' inherited from 'CCUIContentModuleContentViewController' [-Werror,-Wincompatible-property-type]
@property (nonatomic, readonly) CGFloat preferredExpandedContentHeight;
                                        ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:12:40: note: property declared here
@property (nonatomic,readonly) CGFloat preferredExpandedContentHeight;
                                       ^
In file included from CoeusUIModuleContentViewController.m:1:
./CoeusUIModuleContentViewController.h:9:41: error: property type 'CGFloat' (aka 'double') is incompatible with type 'int' inherited from 'CCUIContentModuleContentViewController' [-Werror,-Wincompatible-property-type]
@property (nonatomic, readonly) CGFloat preferredExpandedContentWidth;
                                        ^
/home/mo/theos/include/ControlCenterUIKit/CCUIContentModuleContentViewController.h:13:40: note: property declared here
@property (nonatomic,readonly) CGFloat preferredExpandedContentWidth;
                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[4]: *** [/home/mo/theos/makefiles/instance/rules.mk:209: /home/mo/tweaks/Coeus/.theos/obj/debug/arm64/CoeusUIModuleContentViewController.m.9c276096.o] Error 1
make[4]: *** Waiting for unfinished jobs....
==> Compiling CoeusUILabeledRoundButtonViewController.m (arm64)…
In file included from CoeusUILabeledRoundButtonViewController.m:1:
In file included from ./CoeusUILabeledRoundButtonViewController.h:1:
/home/mo/theos/include/ControlCenterUIKit/CCUIRoundButton.h:14:41: error: declaration of 'UIGestureRecognizerDelegate' must be imported from module 'UIKit.UIGestureRecognizer' before it is required
@interface CCUIRoundButton : UIControl <UIGestureRecognizerDelegate> {
                                        ^
/home/mo/theos/sdks/iPhoneOS14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGestureRecognizer.h:89:11: note: previous declaration is here
@protocol UIGestureRecognizerDelegate <NSObject>
          ^
1 error generated.
make[4]: *** [/home/mo/theos/makefiles/instance/rules.mk:209: /home/mo/tweaks/Coeus/.theos/obj/debug/arm64/CoeusUILabeledRoundButtonViewController.m.9c276096.o] Error 1
==> Compiling CoeusUIContentModule.m (arm64e)…
make[3]: *** [/home/mo/theos/makefiles/instance/bundle.mk:37: /home/mo/tweaks/Coeus/.theos/obj/debug/arm64e/Coeus.bundle/Coeus] Error 2
make[3]: *** Waiting for unfinished jobs....
==> Compiling CoeusUIContentModule.m (arm64)…
make[3]: *** [/home/mo/theos/makefiles/instance/bundle.mk:37: /home/mo/tweaks/Coeus/.theos/obj/debug/arm64/Coeus.bundle/Coeus] Error 2
make[2]: *** [/home/mo/theos/makefiles/instance/bundle.mk:26: internal-bundle-all_] Error 2
make[1]: *** [/home/mo/theos/makefiles/master/rules.mk:119: Coeus.all.bundle.variables] Error 2
make: *** [/home/mo/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2

any help please

**Comment by AzzouQ** [comment]
Hey, this project is not maintained anymore, it's been years since I've played with Theos, so I don't know how to solve this. 😅

All I can say to you is that you can find all the last version compiled .deb at https://github.com/AzzouQ/repo/tree/master/debs. (Don't use Coeus2, it was a new version I had in mind but never had the time to finish it).

If you really want to compile it by yourself, I'm afraid I won't be able to help you, as I don't works on anything Jailbreak related anymore.
